version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: vls
    versions:
    - 0.7.1
