name: Update server

on:
  pull_request:
    branches:
    - master

jobs:
  check-new-settings:
    uses: sublimelsp/workflows/.github/workflows/changed-settings.yaml@v2
    with:
      version_file: 'server/package.json'
      version_regexp: '"@vue/language-server": "([^"]+)"'
      version_transform: 'v{}'
